config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
  namespace :drivers do
  	  resources :map #do
    end
  end

	namespace :api, defaults: {format: 'json'} do
		namespace :v1 do
		namespace :drivers do
			resource :auth
		end
		end
	end
	resources :images
	resources :drivers do
		get 'admin_list', :on => :collection
	end

	devise_for :drivers
	resources :vehicles
	

	devise_for :users

	root :to => redirect('/drivers')

end

app/models/driver.rb
class Driver < ActiveRecord::Base
  #validates :mobile, numericality: {only_integer: true}, presence: true, length: {is: 10}
  #validates :password, length: {minimum: 8}, presence:true
  #validates :license_no, :pan_no, :status, presence: true
  belongs_to :image, :foreign_key => :image_id 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable

  accepts_nested_attributes_for :image
end

app/models/image.rb
class Image < ActiveRecord::Base
  	mount_uploader :picture, PictureUploader
  	has_one :driver, :foreign_key => :image_id 
  	accepts_nested_attributes_for :driver
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  belongs_to :driver
end

app/controllers/admin/drivers/map_controller.rb
class Admin::Drivers::MapController < ApplicationController
  respond_to :html

  def index
	@drivers = Driver.all
	respond_with @drivers
  end
end

app/controllers/api/v1/drivers/auths_controller.rb
require 'securerandom'
require 'json'

module Api
	module V1
		module Drivers
			class AuthsController < ApplicationController
				before_action :authenticate, except: [:create, :new]
				skip_before_action :verify_authenticity_token
				skip_before_action :authenticate_user!
				respond_to :json

				def show
					render json: {:name => @driver.name, :mobile => @driver.mobile, :image => @driver.image}, status: 200
				end

				def create
					api_key = generate_api_key
					@driver = Driver.find_by(mobile: params[:mobile])
					if @driver.nil? or !@driver.valid_password?(params[:password])
						render json: {:is_authorized => "false"}, status: 401 
						return
					else
						@driver.api_key = api_key						
						@driver.save
						render json: {:token => @driver.api_key, :name => @driver.name, :mobile => @driver.mobile, :image => @driver.image}, status: 200
					end
				end		

				def destroy
					@driver.api_key = nil
					@driver.save
					#@driver.destroy
					render json: {}, status: 200
				end
				private
				def generate_api_key
					loop do
						token = SecureRandom.base64.tr('+/=', 'Qrt')
						break token unless Driver.exists?(api_key: token)
					end
				end

				def authenticate
					token = params[:token]	
					if token.nil?
						respond_with status: 401 if token.nil?
						return
					end
					@driver = Driver.where(api_key: token).first if token
					if @driver.nil?						
						render json: {:is_authorized => "false"}, status: 401
						return
					end
				end
			end
		end
	end
end

app/controllers/api/v1/drivers/locations_controller.rb
require 'json'
module Api
	module V1
		module Drivers
			class LocationsController < WebsocketRails::BaseController

				before_action :authenticate
				def initialize_session

				end

				def set_location
					response = "location added"
					failure_response = "Invalid location params"
					begin
						location = message[:location]
						location_driver_id = "location_driver_#{@driver.id}"
						location["time_stamp"] = Time.now.to_i
						$redis.set(location_driver_id, location.to_json)
						trigger_success response
					rescue
						trigger_failure = failure_response
					end
				end

				private
				def authenticate
					token = message[:auth][:token]	
					response = "UnAuthenticated"
					if token.nil?
						trigger_failure response
						return
					end
					@driver = Driver.where(api_key: token).first
					if @driver.nil?		
						trigger_failure response
						return
					end
				end

			end
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @drivers = Driver.includes(:image).all
    @images = Image.all
    respond_with(@drivers, @images)
  end

  def show
    respond_with(@driver)
  end

  def new
    @driver = Driver.new
    @image = @driver.build_image
    respond_with(@driver, @image)
  end

  def edit
    @image = @driver.build_image
    respond_with(@driver, @image)
  end

  def create
    @driver = Driver.new(driver_params)
    @driver.save
    respond_with(@driver)
  end

  def update
    @driver.update(driver_params)
    respond_with(@driver)
  end

  def destroy
    @driver.destroy
    respond_with(@driver)
  end
  def admin_list
  	@drivers = Driver.all
  	respond_with(@drivers)
  end
  
  private
    def set_driver
      @driver = Driver.find(params[:id])
    end

    def driver_params
      params.require(:driver).permit(:name, :mobile, :license_no, :pan_no, :status, :password, image_attributes:[:picture])
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @images = Image.all
    respond_with(@images)
  end

  def show
    respond_with(@image)
  end

  def new
    @image = Image.new
    respond_with(@image)
  end

  def edit
  end

  def create
    @image = Image.new(image_params)
    @image.save
    respond_with(@image)
  end

  def update
    @image.update(image_params)
    respond_with(@image)
  end

  def destroy
    @image.destroy
    respond_with(@image)
  end

  private
    def set_image
      @image = Image.find(params[:id])
    end

    def image_params
      params.require(:image).permit(:picture)
    end
end

app/controllers/locations_controller.rb
#module Api
	#	module V1
	#		module Drivers
	class LocationsController < WebsocketRails::BaseController
		before_action :authenticate
		def initialize_session

		end

		def create
			@location = params[:location]
			$redis.set(@driver.id,@location)
			render json: {}, status: 200
		end

		def authenticate
			token = params[:token]	
			if token.nil?
				respond_with status: 401 if token.nil?
				return
			end
			@driver = Driver.where(api_key: token).first if token
			if @driver.nil?					
				render json: {:is_authorized => "false"}, status: 401
				return
			end
		end

	end
	#		end
	#	end
#end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @vehicles = Vehicle.all
    respond_with(@vehicles)
  end

  def show
    respond_with(@vehicle)
  end

  def new
    @vehicle = Vehicle.new
    respond_with(@vehicle)
  end

  def edit
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    @vehicle.save
    respond_with(@vehicle)
  end

  def update
    @vehicle.update(vehicle_params)
    respond_with(@vehicle)
  end

  def destroy
    @vehicle.destroy
    respond_with(@vehicle)
  end

  private
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    def vehicle_params
      params.require(:vehicle).permit(:make, :model, :year, :registration_no, :driver_id, :driver_id)
    end
end

app/helpers/admin/drivers/map_helper.rb
module Admin::Drivers::MapHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/admin/drivers/map/index.html.erb
<style>
			#map-canvas {
				height: 500px;
				margin-top: 40px;
				padding: 10px;
			}
			
</style>

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places,geometry&sensor=false"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script type="text/javascript">
    

function initialize() {
  var myLatlng = new google.maps.LatLng(17.36, 78.47);
  var mapOptions = {
    zoom: 8,
    center: myLatlng
  }
  
  var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
  <% @drivers.each do |driver| %>
   
  <% loc = $redis.get("location_driver_#{driver.id}") unless driver.nil? %>;
  <% unless loc.nil? or loc.empty? %>
  var location =  <%=raw loc %>;
  var contentString = '<b>Name: </b>'+"<%=driver.name%>"+'<br><b>Phone: </b>'+"<%=driver.mobile.to_s%>"+
  '<br><b>Image: </b>'+ '<%=image_tag driver.image.picture_url(:thumb) unless driver.image.nil? or driver.image.picture.nil? %>';
  var infowindow = new google.maps.InfoWindow({
      content: contentString
  });
  
  var Latlng = new google.maps.LatLng(parseFloat(location["lat"]),parseFloat(location["lng"]));
  debugger;
  //map.setCenter(myLatlng);
  var marker = new google.maps.Marker({
  	  
      position: Latlng,
      map: map,      
      icon: '../../../assets/green\.jpg'
  });
  if(Date.now()-location["time_stamp"] < 30000){marker.icon = '../../../assets/green\.jpg';}
  else marker.icon = '../../../assets/red\.jpg';
   
  google.maps.event.addListener(marker, 'click', function() {
    infowindow.open(map,marker);
  });

  <%end%>
  <%end%>
}
google.maps.event.addDomListener(window, 'load', initialize);
      
</script>

<div id = "test" style="float: right"></div>
<div id="map-canvas">	
</div>

app/views/drivers/_form.html.erb
<%= form_for(@driver, html:{:multipart => true, class:"form-horizontal"}) do |f| %>
	<% if @driver.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@driver.errors.count, "error") %> prohibited this driver from being saved:</h2>

			<ul>
				<% @driver.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="form-group">
		<%= f.label :name, class: "col-sm-2 control-label" %>
		<div class="col-sm-10">
			<%= f.text_field :name , class: "form-control input-lg" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :mobile, class: "col-sm-2 control-label" %>
		<div class="col-sm-10">
			<%= f.text_field :mobile, class: "form-control input-lg" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :license_no, class: "col-sm-2 control-label" %>
		<div class="col-sm-10">
			<%= f.text_field :license_no, class: "form-control input-lg" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :pan_no, class: "col-sm-2 control-label lg" %>
		<div class="col-sm-10">
			<%= f.text_field :pan_no,class: "form-control input-lg" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.fields_for :image do |builder| %>
			<%= builder.label :picture, class: "col-sm-2 control-label lg"%>
		<div class="col-sm-10">
			<%= builder.file_field :picture, class: "form-control"%>
		</div>
	<% end %>
	</div>
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<div class="checkbox">
				<%= f.check_box :status %>
				<%= f.label :is_active%>
			</div>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :password, class: "col-sm-2 control-label" %>
		<div class="col-sm-10">
			<%= f.text_field :password, class: "form-control input-lg" %>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<%= f.submit class: "btn btn-primary" %>
		</div>
	</div>
<% end %>

app/views/drivers/admin_list.html.erb
<h1>Admin-List</h1>


<div class="table table-striped">
	<table class="table">
		<thead>
			<tr>
				<th>Name</th>
				<th>Mobile</th>
				<th>License no</th>
				<th>Pan no</th>
				<th>Status</th>
				<th>Encrypted_password</th>
			</tr>
		</thead>

		<tbody>
			<% @drivers.each do |driver| %>
				<tr>
					<td><%= driver.name %></td>
					<td><%= driver.mobile %></td>
					<td><%= driver.license_no %></td>
					<td><%= driver.pan_no %></td>
					<td><%= driver.status %></td>
					<td><%= driver.encrypted_password %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>
<br>
<%= link_to 'New Driver', new_driver_path, :class => 'btn btn-primary' %>

app/views/drivers/edit.html.erb
<h1>Editing driver</h1>

<%= render 'form' %>

<%= link_to 'Show', @driver %> |
<%= link_to 'Back', drivers_path %>

app/views/drivers/index.html.erb
<h1>Listing drivers</h1>

<div class="table table-striped">
	<table class="table">
		<thead>
			<tr>
				<th>Name</th>
				<th>Mobile</th>
				<th>License no</th>
				<th>Pan no</th>
				<th>Image</th>
				<th>Status</th>
				<th>Encrypted_password</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% @drivers.each do |driver| %>
				<tr>
					<td><%= driver.name %></td>
					<td><%= driver.mobile %></td>
					<td><%= driver.license_no %></td>
					<td><%= driver.pan_no %></td>
					<td><%= image_tag driver.image.picture_url(:thumb) unless driver.image.nil? or driver.image.picture.nil? %></td>
					<td><%= driver.status %></td>
					<td><%= driver.encrypted_password %></td>
					<td><%= link_to 'Show', driver, :class => 'btn btn-mini' %></td>
					<td><%= link_to 'Edit', edit_driver_path(driver), :class => 'btn btn-mini' %></td>
					<td><%= link_to 'Destroy', driver, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>
<br>

<%= link_to 'New Driver', new_driver_path, :class => 'btn btn-primary' %>

app/views/drivers/new.html.erb
<h3 align="center">New driver</h3>

<%= render 'form' %>

<%= link_to 'Drivers List', drivers_path, class: 'btn btn-mini' %>

app/views/drivers/show.html.erb
<p id="notice"><%= notice %></p>
<script>
	(function() {	
		var jobj = {"mobile": <%=@driver.mobile %>, "token": "2lraZndx5Nmh3qztZfOABQtt","location":{"lat":"17.36","lng":"78.47", "accuracy":"100"}};
		var dispatcher = new WebSocketRails('192.168.0.145:4000/websocket');
		//var dispatcher = new WebSocketRails('localhost:3000/websocket');
		
		var success = function(response) {
			console.log("Wow it worked: "+response.message);
		}
		var failure = function(response) {
			console.log("That just totally failed: "+response.message);
		}
		//dispatcher.on_open = function() {
		 // dispatcher.trigger("api.v1.drivers.create", jobj);
		//}
	})();
</script>

<p>
<strong>Name:</strong>
<%= @driver.name %>
</p>

<p>
<strong>Mobile:</strong>
<%= @driver.mobile %>
</p>

<p>
<strong>License no:</strong>
<%= @driver.license_no %>
</p>

<p>
<strong>Pan no:</strong>
<%= @driver.pan_no %>
</p>

<p>
<strong>Image_Id:</strong>
<%= @driver.image_id %>
</p>

<p>
<strong>Status:</strong>
<%= @driver.status %>
</p>

<p>
<strong>Encrypted password:</strong>
<%= @driver.encrypted_password %>
</p>

<%= link_to 'Edit', edit_driver_path(@driver) %> |
<%= link_to 'Back', drivers_path %>

app/views/images/_form.html.erb
<%= form_for(@image, html:{:multipart => true, class:"form-horizontal"}) do |f| %>
	<% if @image.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

			<ul>
				<% @image.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="form-group">
		<%= f.label :picture, class: "col-sm-2 control-label" %>
		<div class="col-sm-10">
			<%= f.file_field :picture,accept: 'image/png, image/gif, image/jpeg'%>
		</div>
	</div> 
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<%= f.submit class: "btn btn-default" %>
		</div>
	</div>

<% end %>

app/views/images/_sam.html.erb
Hello sample file

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<h1>Listing images</h1>

<table>
  <thead>
    <tr>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.picture %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Picture:</strong>
  <%= @image.picture %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Croncab</title>
		<link rel="stylesheet" href="../../assets/bootstrap.min.css">
		<link rel="stylesheet" href="../../assets/bootstrap-theme.css">

		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="/">CronCab</a>
			</div>
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
					<li class="active">
					<a href="/drivers/admin_list">Admin List</a>
					</li>
				</ul>
				<p class="navbar-text pull-right">
				<% if user_signed_in? %>
					Logged in as <strong><%= current_user.email %></strong>
					<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
					<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
				<% else %>
					<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %>
					<%= link_to "Login", new_user_session_path, :class => 'navbar-link' %>
				<% end %>
				</p>
			</div>
		</div>
		</nav>

		<div class="container">
			<% if notice %>
				<p class="alert alert-success"><%= notice %></p>
			<% end%>
			<% if alert %>
				<p class="alert alert-danger"><%= alert%></p>
			<% end %>
			<%= yield %>



			<script src="../../assets/bootstrap.js"></script>
		</body>
	</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% @vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :make %><br>
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :registration_no %><br>
    <%= f.number_field :registration_no %>
  </div>
  <div class="field">
    <%= f.label :driver_id %><br>
    <%= f.number_field :driver_id %>
  </div>
  <div class="field">
    <%= f.label :driver_id %><br>
    <%= f.text_field :driver_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing vehicle</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<h1>Listing vehicles</h1>

<table>
  <thead>
    <tr>
      <th>Make</th>
      <th>Model</th>
      <th>Year</th>
      <th>Registration no</th>
      <th>Driver</th>
      <th>Driver</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.make %></td>
        <td><%= vehicle.model %></td>
        <td><%= vehicle.year %></td>
        <td><%= vehicle.registration_no %></td>
        <td><%= vehicle.driver_id %></td>
        <td><%= vehicle.driver %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %>

app/views/vehicles/new.html.erb
<h1>New vehicle</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Make:</strong>
  <%= @vehicle.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @vehicle.model %>
</p>

<p>
  <strong>Year:</strong>
  <%= @vehicle.year %>
</p>

<p>
  <strong>Registration no:</strong>
  <%= @vehicle.registration_no %>
</p>

<p>
  <strong>Driver:</strong>
  <%= @vehicle.driver_id %>
</p>

<p>
  <strong>Driver:</strong>
  <%= @vehicle.driver %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>